# .gitlab-ci.yml

image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2


build:
  stage: build
  script:
    - docker-compose.sh build

deploy:
  stage: deploy
  script:
    - echo "Starting deployment..."
    - docker-compose.sh up -d
